# Generated by Django 5.1.6 on 2025-03-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_story_bookmarks_remove_story_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='bookmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
